add --list option
akameco/touch-alt pull request #6
Opened 2018-10-09 13:34 UTC by macinjoke

**What**:
`--list` オプションを追加しました。 https://github.com/akameco/touch-alt/issues/4 の対応。 

**Why**:
現状どのようなテンプレートファイルがあるか知る機能があれば便利だから。

**How**:
結果を標準出力に出す必要があったので、 `index.js`  の関数を文字列を返し、 `cli.js` 側で返された文字列を出力するように変更しました。(てすと

**Checklist**:

* [ ] Documentation
* [ ] Tests
* [ ] Ready to be merged 
* [ ] Added myself to contributors table

2018-10-10 14:31 UTC, akameco approved these changes

2018-10-10 14:31 UTC, akameco commented on index.js
> +        return 'no template files'
英語がよくわからない感じです。`Not found`的な文言のほうがわかりやすそうです

2018-10-10 14:31 UTC, akameco commented on index.js
> +    if (opts.list) {
このネストはまとめた方がよさそうです

2018-10-10 14:31 UTC, akameco commented on index.js
> +      return files.join('\n')
インターフェイスとして文字列を返すのは違和感があります

2018-10-10 14:31 UTC, akameco commented on cli.js
> +  -l, --list        show template file list
show → `Show`

2018-10-10 14:31 UTC, akameco commented on cli.js
> +      list: {
`--list`だとちょっと一般化しすぎる気がするので、`--show-all-templates`ぐらい長くてもいいかなという気持ちもあります。

2018-10-10 14:34 UTC, akameco requested changes

2018-10-10 14:34 UTC, akameco commented on cli.js
> +  -l, --list        show template file list
`show` → `Show`

2018-10-10 14:34 UTC, akameco commented on cli.js
> +      list: {
一般化しすぎる気がするので、長い名前でもよさそうです。

2018-10-10 14:34 UTC, akameco commented on cli.js
> +  const output = fn(cli.input[0], cli.flags)
インターフェイスとして文字列を返すのは微妙な感じがします

2018-10-10 14:34 UTC, akameco commented on index.js
> +        return 'no template files'
英語がよくわからない感じです。Not found的な文言のほうがわかりやすそうです

2018-10-10 14:34 UTC, akameco commented on index.js
> +    if (opts.list) {
このネストはまとめた方がよさそうです

2018-10-10 14:34 UTC, akameco commented on index.js
> +      return files.join('\n')
インターフェイスとして文字列を返すのは違和感があります

2018-10-11 04:34 UTC, macinjoke commented on cli.js
> +      list: {
tmp-list とかでよいですか？

2018-10-11 12:27 UTC, akameco commented
冷静に考えましが、クローズさせていただきます。
理由は、`ls ~/.touch-alt`だけで列挙できるのと、cliツールは一つのことに集中すべきだと思うので別にこのツールに必須ではないなと判断しました。
ただ、テンプレートのファイルの場所はドキュメントに書いておくべきだと思ったので書いておきます。

2018-10-11 12:27 UTC, closed without merging

2018-10-11 12:34 UTC, macinjoke commented
了解です！